---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slow-cooker
  namespace: leaderboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slow-cooker
    spec:
      containers:
      - image: buoyantio/slow_cooker
        imagePullPolicy: Always
        name: slow-cooker
        env:
          - name: QPS
            value: "100"
          - name: CONCURRENCY
            value: "10"

        command: ["/bin/sh", "-c"]
        args:
          - |-
            slow_cooker -qps ${QPS} -concurrency ${CONCURRENCY} http://web:8080

        resources:
          requests:
            cpu: 500m
