---

apiVersion: v1
kind: Namespace
metadata:
  name: leaderboard

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: leaderboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: thomasr/hpa-frontend:v1
          imagePullPolicy: Always
          name: web
          command: ["/code/bin/run.sh"]
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 1000m

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: leaderboard
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: leaderboard
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:5-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: leaderboard
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 3306
      targetPort: 6379
